[package]
name = "deno_server_plugin"
version = "0.0.1"
authors = ["木杉"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = "0.38.0"
rust-crypto = "^0.2"
serde_json = "1.0"
rustc-serialize = "0.3"
