name: deploy

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
        with:
          deno-version: 0.38.0
      - name: Build Image
        env:
          DockerUsername: ${{ secrets.DockerUsername }}
          DockerPassword: ${{ secrets.DockerPassword }}
        run: |
          docker login -u $DockerUsername -p $DockerPassword
          docker build -t zhmushan/clicli_server .
          docker push zhmushan/clicli_server
  deploy:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DeployHost }}
          username: ${{ secrets.DeployUsername }}
          password: ${{ secrets.DeployPassword }}
          port: 22
          script: whoami